wandb_version: 1

K_epochs:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662024267.732818
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.10.4
      5: 0.13.2
      8:
      - 5
batchsize:
  desc: null
  value: 2
entropy_ratio:
  desc: null
  value: 0.01
eps_clip:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.000181
mse_ratio:
  desc: null
  value: 0.5
update_interval:
  desc: null
  value: 4
weight_decay:
  desc: null
  value: 0.039428
